// Code generated by MockGen. DO NOT EDIT.
// Source: server/inv/api.go

// Package inv is a generated GoMock package.
package inv

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockInventoryService is a mock of InventoryService interface.
type MockInventoryService struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryServiceMockRecorder
}

// MockInventoryServiceMockRecorder is the mock recorder for MockInventoryService.
type MockInventoryServiceMockRecorder struct {
	mock *MockInventoryService
}

// NewMockInventoryService creates a new mock instance.
func NewMockInventoryService(ctrl *gomock.Controller) *MockInventoryService {
	mock := &MockInventoryService{ctrl: ctrl}
	mock.recorder = &MockInventoryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryService) EXPECT() *MockInventoryServiceMockRecorder {
	return m.recorder
}

// ReserveSeat mocks base method.
func (m *MockInventoryService) ReserveSeat(firstName, lastName, email string) (Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveSeat", firstName, lastName, email)
	ret0, _ := ret[0].(Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReserveSeat indicates an expected call of ReserveSeat.
func (mr *MockInventoryServiceMockRecorder) ReserveSeat(firstName, lastName, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveSeat", reflect.TypeOf((*MockInventoryService)(nil).ReserveSeat), firstName, lastName, email)
}
